kind: Namespace
apiVersion: v1
metadata:
  name: petclinic

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: petclinic-configmap
  namespace: petclinic
data:
  spring.datasource.username: postgres
  spring.datasource.driver-class-name: org.postgresql.Driver
  spring.datasource.url: jdbc:postgresql://postgres:5432/petclinic

---
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-secret
  namespace: petclinic
type: Opaque
data:
  spring.datasource.password: MTJQb3N0Z3Jlc0Ah

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  petclinic-application
spec:
  prefix: /
  service: petclinic:8080
